---
# ROLE: fedora
# roles/fedora/tasks/main.yml
#

- name: setup install directory
  set_fact:
    install_path: /home/{{ ansible_ssh_user }}/install
    
- name: ensure install directory exists
  file:
    path: '{{ install_path }}'
    state: directory

- name: install servlet container package
  become: yes
  package: name=tomcat7 state=present

- name: download fedora
  get_url: url=http://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_version }}/fcrepo-webapp-{{ fedora_version }}.war owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} dest={{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war timeout=100

- name: make fedora data dir
  file: owner=tomcat7 group=tomcat7 state=directory path=/opt/fedora-data
  become: yes

- name: check fedora.war
  stat: path=/var/lib/tomcat7/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  become: yes
  command: cp {{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war /var/lib/tomcat7/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options for Fedora 4.6+
  become: yes
  template:
    src: tomcat7.j2
    dest: "{{ fedora_config_file }}"
    owner: tomcat7
    group: tomcat7
    backup: yes
  when:
    - fedora_version | match("^4\.[6-9]\.[0-9]")

- name: set port for tomcat
  become: yes
  replace:
    dest: /etc/tomcat7/server.xml
    regexp: "8080"
    replace: "{{ tomcat_port }}"

- name: add log rotation for catalina.out (tomcat/fedora logs)
  become: yes
  template: src=logrotate-tomcat dest=/etc/logrotate.d/tomcat7 backup=yes

- name: restart servlet
  become: yes
  service: name=tomcat7 enabled=yes state=restarted
