---
# ROLE: packages
# roles/pip/tasks/main.yml
#
# installs pip - required for python packages

- name: install python tools
  package: name={{ item }} state=present
  become: yes
  with_items:
    - python-setuptools
    - python-dev
    - build-essential
    - python3-pip
